### ISSUE TITLE
handoff.ip is missing from riak_core.schema

### ISSUE THREAD

**Issue by jrwest** [basho/riak_core#634]
when it is added we should add a validation to ensure people _do not_ set it to `127.0.0.1` -- it can cause problems.

**Comment by andrewjstone** [comment]
Fixed by #653

**Comment by Basho-JIRA** [comment]
This was resolved a while ago by https://github.com/basho/riak_core/pull/653 — time to learn how to mark a jira issue closed. 

**_[posted via JIRA by Alex Berghage]**_

**Comment by Basho-JIRA** [comment]
Reopening b/c JIRA workflow was screwy when I closed this, so it never got a resolution field and still shows in my dash. 

**_[posted via JIRA by Alex Berghage]**_
